### ISSUE TITLE
ReAdd Combat Extended support

### ISSUE THREAD

**Issue by jinlan** [Adventurer13/ExpandedWoodworking#15]
Combat Extended is runnable now ( although still incomplete ) .

**Comment by Adventurer13** [comment]
I'll add it back once updated to 1.0. While playable, any changes I make to the patch now for compatibility, may have to be made again once it is updated as it is still in progress. Rather than make multiple updates to maintain compatibility as Combat Extended is being updated, I want to do it all at once when it is at stable release.
