### ISSUE TITLE
Lord of the Rims Patches

### ISSUE THREAD

**Issue by Adventurer13** [Adventurer13/ExpandedWoodworking#22]
For discussion. suggestions, and progress relating to the Lord of the Rims mods and compatibility with Expanded Woodworking. Any help is requested and very appreciated.

[Areas of help/suggestions](https://github.com/Adventurer13/ExpandedWoodworking/issues/22#issuecomment-455840000): 
- Finding anywhere _WoodLog_ is used within (except where used as fuel)
- ~~Trees~~
- ~~Color of wood~~ 
- ~~Stats of wood~~
- ~~Textures~~ 
  
  
# [Lord of the Rims](https://github.com/Lord-of-the-Rims-DevTeam) 

- [x] Tested to work

### [Men and Beasts](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Men-and-Beasts/tree/master/Defs)
- Gondor 
  - Buildings
    - [x] Beacons
  - Weapons 
    - [x] Spear (+ masking)
    - [x] Bow

### [Moria Goblins](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---MoriaGoblins)
- Buildings
  - [x] HIve, Hut, Drum 
- Walls
  - [x] Orc Wall

### [The Third Age](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---The-Third-Age)
- Lighting
  - [x] Wall Sconce
- Scenario
  - [x] Third Age Fellowship (if using Elves)

### [Misty Mountains Goblins](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---MistyMountainGoblins)
- Walls
  - [x] Orc Wall

### [Orcs and Goblins](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Orcs-and-Goblins)
- Walls
  - [x] Orc Wall

### [Elves](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Elves)
- Faction
  - [x] Elven Factions (add lumber)
- Scenario
  - [x] Elves - A New Territory
- Terrain
  - [x] Floors
- Items
  - [x] Mallorn Wood / Lumber color: (240,218,165)
  - [x] Golden Birch Wood / Lumber color: (237,220,149) (in between [silver](https://www.wood-database.com/silver-birch/) and [sweet](https://www.wood-database.com/sweet-birch/) birch for stats)
- Weapons (melee weapons use Metallic as primary component, won't patch, instead use mixed lumber)  
  - [x] Bows (Mirkwood, Galadhrim) (+ masking)
- Plants
  - [x] Mallorn Tree
  - [x] Golden Birch Tree

### [Hobbits](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Hobbits) 
(Nothing needs patching)

### [Dwarves](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Dwarves)
- Buildings
  - Furniture
    - [x] Game Table
  - Production
    - [x] Fermenting Barrel (mead) (texture and stuffed)
- Items
  - Shields (Already colored, won't patch, use mixed lumber)
  - Toys
    - [x] Puzzle Box 
    - [x] Marble Labyrinth 
  - Weapons 
    - [x] Spear (+ masking)
    - [x] Bow (+ masking)
    - [x] Crossbow (+ masking)

### [Unlimited](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Unlimited)
- Lighting
  - [x] Wall Sconce
- Scenario
  - [x] Third Age Fellowship (if using Elves)

### [Ents](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Ents)
(Skipping--works fine as is.) 

### [Wizardry](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Wizardry)
(Nothing needs patching)

Requested by Issue #21

**Comment by BlueTressym** [comment]
Umm, I haven't used GitHub and I really don't know what I'm doing but I'd like to help.  What is the best way to get the info you need, since I have the mods, and how should I present it?  As in, do I just copy/paste bits of stats from the plants etc?  Should I attach the .xml file?

**Comment by Adventurer13** [comment]
I wouldn't ask you to do anything you don't know how to do. Honestly, if helping out with these:

> - Finding anywhere WoodLog is used within (except where used as fuel)
> - Trees

just the file path and defname is perfect.

If helping with these:

> - Color of wood
> - Stats of wood

suggestions of a color using RGB values is perfect, but even a tree species or picture with a certain color as a recommendation is great too. I can use a color picker to get the exact rgb values, so that isn't a problem. For stats, it is a bit trickier unless I have access to actual values of the wood of a tree species. For example, the stats below for the birch I used in EW came from the average dried weight, janka hardness, and other details of [Paper Birch on The Wood Database](https://www.wood-database.com/paper-birch/) plus some calculations/subjectivity.

`<Mass>0.6</Mass>` (rounded average dried weight)
`<MarketValue>1.5</MarketValue>` (balanced upon commonality, hit points, beauty, and work stats) 
`<DeteriorationRate>6</DeteriorationRate>` (Rot resistance details translated into numbers)
`<commonality>0.8</commonality>` (balanced upon how common tree in-game and market value) 
`<MaxHitPoints>0.45</MaxHitPoints>` (half of janka hardness + some subjectivity for balance)
`<Beauty>1.3</Beauty>` (Qwynn's subjectivity as well as my subjectivity)
`<WorkToMake>0.4</WorkToMake>` (rounded half of janka hardness)
`<WorkToBuild>0.4</WorkToBuild>` (rounded half of janka hardness)
`<DoorOpenSpeed>1.2</DoorOpenSpeed>` (1.8 - mass) most of the time

However, Cecropia, Cocoa, Drago, Saguaro, and Bamboo were guesstimated after hours of searching for information, so any suggestions and/or a _similar to_ make it quicker and easier to give stats to fantasy woods. I don't know whether to use an aspen or a birch for the golden birch in LotR given their [appearance in the mod](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Elves/tree/master/Textures/Things/Plant/GoldenBirch) and then to determine which species of birch or aspen to use for example. Any comments on such is helpful.

If anyone sees this comment and is confused with the texture work mentioned in the first post, I am referring to the fact the blade won't remain white/silver when using different woods. This is unwanted and so requires another image for masking only the handle. Otherwise, I'll leave it as is (using mixed lumber) or require it be made out of another wood type (haven't yet decided which, but probably either mallorn or golden birch).

**Comment by BlueTressym** [comment]
Hi. Thank you; I'll get on to that. I've got an important family
get-together today but I'll see if I can get as much of that looked at as
possible later or tomorrow.


On 20 Jan 2019 05:50, "Adventurer13" <notifications@github.com> wrote:

I wouldn't ask you to do anything you don't know how to do. Honestly, if
helping out with these:


   - Finding anywhere WoodLog is used within (except where used as fuel)
   - Trees

just the file path and defname is perfect.

If helping with these:


   - Color of wood
   - Stats of wood

suggestions of a color using RGB values is perfect, but even a tree species
or picture with a certain color as a recommendation is great too. I can use
a color picker to get the exact rgb values, so that isn't a problem. For
stats, it is a bit trickier unless I have access to actual values of the
wood of a tree species. For example, the stats below for the birch I used
in EW came from the average dried weight, janka hardness, and other details
of Paper Birch on The Wood Database
<https://www.wood-database.com/paper-birch/> plus some
calculations/subjectivity.

<Mass>0.6</Mass> (rounded average dried weight)
<MarketValue>1.5</MarketValue> (balanced upon commonality, hit points,
beauty, and work stats)
<DeteriorationRate>6</DeteriorationRate> (Rot resistance details translated
into numbers)
<commonality>0.8</commonality> (balanced upon how common tree in-game and
market value)
<MaxHitPoints>0.45</MaxHitPoints> (half of janka hardness + some
subjectivity for balance)
<Beauty>1.3</Beauty> (Qwynn's subjectivity as well as my subjectivity)
<WorkToMake>0.4</WorkToMake> (rounded half of janka hardness)
<WorkToBuild>0.4</WorkToBuild> (rounded half of janka hardness)
<DoorOpenSpeed>1.2</DoorOpenSpeed> (1.8 - mass) most of the time

However, Cecropia, Cocoa, Drago, Saguaro, and Bamboo were guesstimated
after hours of searching for information, so any suggestions and/or a *similar
to* make it quicker and easier to give stats to fantasy woods. I don't know
whether to use an aspen or a birch for the golden birch in LotR given
their appearance
in the mod
<https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Elves/tree/master/Textures/Things/Plant/GoldenBirch>
and then to determine which species of birch or aspen to use for example.
Any comments on such is helpful.

If anyone sees this comment and is confused with the texture work mentioned
in the first post, I am referring to the fact the blade won't remain
white/silver when using different woods. This is unwanted and so requires
another image for masking only the handle. Otherwise, I'll leave it as is
(using mixed lumber) or require it be made out of another wood type
(haven't yet decided which, but probably either mallorn or golden birch).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Adventurer13/ExpandedWoodworking/issues/22#issuecomment-455840000>,
or mute the thread

**Comment by BlueTressym** [comment]
https://docs.google.com/document/d/1PE3qgi5cYNPJZo2xXw88PAL5vapxlg-5o-SFuxVq7hU/edit?usp=sharing

Lord of the Rims - The Third Age
Occurrences of ‘WoodLog’
Defs\LotR_Lighting.xml
<defName>LotR_WallSconce</defName>

Defs\LotR_Scenario.xml
<defName>LotR_SimpleColony</defName>
<li Class="ScenPart_ScatterThingsNearPlayerStart">
          <def>ScatterThingsNearPlayerStart</def>
          <thingDef>WoodLog</thingDef>
          <count>300</count>
</li>
<defName>LotR_SimpleFellowship</defName>
<li Class="ScenPart_ScatterThingsNearPlayerStart">
          <def>ScatterThingsNearPlayerStart</def>
          <thingDef>WoodLog</thingDef>
          <count>300</count>
</li>

Lord of the Rims - Unlimited
Occurrences of ‘WoodLog’
Defs\LotR_Lighting.xml
<defName>LotR_WallSconce</defName>

Defs\LotR_Scenario.xml
<defName>LotR_SimpleColony</defName>
        <li Class="ScenPart_ScatterThingsNearPlayerStart">
          <def>ScatterThingsNearPlayerStart</def>
          <thingDef>WoodLog</thingDef>
          <count>300</count>
        </li>

<defName>LotR_SimpleFellowship</defName>
        <li Class="ScenPart_ScatterThingsNearPlayerStart">
          <def>ScatterThingsNearPlayerStart</def>
          <thingDef>WoodLog</thingDef>
          <count>300</count>
        </li>

Lord of the Rims - Dwarves
Occurrences of ‘WoodLog’
Defs\ScenarioDefs\LotRD_Scenarios.xml
<defName>LotRD_Homeless</defName>

        <li Class="ScenPart_ScatterThingsNearPlayerStart">
          <def>ScatterThingsNearPlayerStart</def>
          <thingDef>WoodLog</thingDef>
          <count>300</count>
        </li> 

Defs\ThingDefs_Buildings/LotRD_Furniture.xml
<defName>LotRD_GameTable</defName>

Defs\ThingDefs_Buildings/LotRD_Production.xml
<defName>LotRD_FermentingBarrel</defName>

Defs\ThingDefs_Items/LotRD_ApparelShield.xml
<defName>LotRD_DwarfStandardShield</defName>

Defs\ThingDefs_Items/LotRD_Toys.xml
<defName>LotRD_DwarfPuzzleBox</defName>
<defName>LotRD_DwarfMarbleLabyrinth</defName>

Defs\ThingDefs_Items/LotRD_WeaponsBow.xml
<defName>LotRD_Bow_Dwarven</defName>
<defName>LotRD_Bow_DwarvenCross</defName>

Lord of the Rims - Elves
Occurrences of ‘WoodLog’
Defs\ScenarioDefs\LotRE_Scenarios.xml
<defName>LotRE_ANewTerritory</defName>

        <li Class="ScenPart_ScatterThingsNearPlayerStart">
          <def>ScatterThingsNearPlayerStart</def>
          <thingDef>WoodLog</thingDef>
          <count>300</count>
        </li>

Defs\ThingDefs_Items/LotRE_WeaponsBow.xml
<defName>LotRE_Bow_Mirkwood</defName>
<defName>LotRE_Bow_Galadhrim</defName>

Defs\ThingDefs_Items/LotRE_WeaponsSword.xml
<defName>LotRE_MeleeWeapon_WhiteKnives</defName>
<defName>LotRE_MeleeWeapon_Saber</defName>
<defName>LotRE_MeleeWeapon_Lhang</defName>

Lord of the Rims - Hobbits
Occurrences of ‘WoodLog’
Defs\ScenarioDefs\LotRH_Scenarios.xml
<defName>LotRH_AnUnexpectedColony</defName>

        <li Class="ScenPart_ScatterThingsNearPlayerStart">
          <def>ScatterThingsNearPlayerStart</def>
          <thingDef>WoodLog</thingDef>
          <count>300</count>
        </li>

**Comment by Adventurer13** [comment]
Thanks for the information! There are a few things I missed that need patching that you found. I could do silver birch, probably use stats that are between those of silver and sweet birch then for LotR's golden birch just to differentiate it more while still keeping within the birch species. This also gives me a starting color to work with as well, so that is great.

From my testing, the commonality factor refers to the chance of a trader (that sells wood) will have it in their stock for sale. Given the amount of wood types added by EW it can be a slim chance of the that occurring for some types (like black palm and cocoa) in comparison to others (like poplar). Most traders only have 2-5 wood types of each log and lumber in stock with what I set it to. So with my birch example above, I assume it is an 80% chance these traders will have a stock of birch logs as one of their types of logs.

**Comment by BlueTressym** [comment]
Thank you for the 'commonality' explanation.  

Is there anything more you'd like me to look at?

**Comment by Adventurer13** [comment]
> Is there anything more you'd like me to look at?

Nope, just open another issue if you find anything else as the mods from Lord of the Rims update as I won't know otherwise.
