### ISSUE TITLE
Patch operation failure for FermentingBarrel 

### ISSUE THREAD

**Issue by Luinithil** [Adventurer13/ExpandedWoodworking#9]
Received this error on starting a new game:

`[Expanded Woodworking B18] Patch operation Verse.PatchOperationSequence(count=2, lastFailedOperation=Verse.PatchOperationAdd(/Defs/ThingDef[defName = "FermentingBarrel"])) failed
file: D:\Games\steamapps\workshop\content\294100\1082915328\Patches\ExpWoodVanilla.xml
Verse.Log:Error(String)
Verse.PatchOperation:Complete(String)
Verse.PatchOperationSequence:Complete(String)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
`
Full error log here: https://gist.github.com/23ea107122adcc72b7aebc0158d8831f

Current modlist attached below. Note that I currently have dummy mods (only metadata with no actual content) enabled for personal ease of sorting. 
[modlist.txt](https://github.com/Adventurer13/ExpandedWoodworking/files/1693048/modlist.txt)

**Comment by Adventurer13** [comment]
Patch failed errors aren't usually a concern, although, I do like to be notified of them so that I may have them not appear and can adjust the specific patch for a future update. I appreciate you letting me know of this, however, I have no idea which mod loaded before Expanded Woodworking is causing it. There are _many_ mods loaded before EW and I didn't notice any of the usual offenders when looking through your error log.

I am going to describe what the failed patch is doing and maybe you can help me out with narrowing it down since you probably know more about the mods you are using than I do. 

This specific patch is allowing you to be able to build the fermenting barrel out of the different lumber types and makes it take 30 of the material to make it. The cost is not important and is not what is causing it to fail, rather the change of allowing it to be made of different lumber types is. It fails because some mod loaded before it already changes the fermenting barrel to use multiple material types. 

This is what I need to know: _the mod(s) that edit the fermenting barrel_. 
Once I have this, I can much more easily narrow down what mod and where it is occurring, and then make an exception for it so the error no longer occurs and appears.

If you are okay with and don't mind receiving this error on every load, let me know if the following is possible:
- Can make the fermenting barrel out of multiple materials (including multiple lumber types, specifically)

If possible, this patch error can be completely neglected since it is causing no problems within the game.

On a side note, this is one of the reasons I am _experimenting_ with a different patching system ([ModCheck](https://ludeon.com/forums/index.php?topic=36534.0)) than the one Rimworld has naturally.
